services:
  yb-master:
    image: yugabytedb/yugabyte:2.14.1.0-b36
    container_name: yb-master-n1
    command:
      [
        "/home/yugabyte/bin/yb-master",
        "--fs_data_dirs=/mnt/master",
        "--master_addresses=yb-master-n1:7100",
        "--rpc_bind_addresses=yb-master-n1:7100",
        "--replication_factor=1"
      ]
    ports:
      - "7000:7000"
    volumes:
      - yb-master-data-1:/mnt/master
    environment:
      SERVICE_7000_NAME: yb-master

  yb-tserver:
    image: yugabytedb/yugabyte:2.14.1.0-b36
    container_name: yb-tserver-n1
    command:
      [
        "/home/yugabyte/bin/yb-tserver",
        "--fs_data_dirs=/mnt/tserver",
        "--start_pgsql_proxy",
        "--enable_ysql",
        "--rpc_bind_addresses=0.0.0.0:9100",
        "--tserver_master_addrs=yb-master-n1:7100",
        "--ysql_enable_auth=true",
        "--use_cassandra_authentication=true"
      ]
    ports:
      - "9042:9042"
      - "5433:5433"
      - "9000:9000"
    volumes:
      - yb-tserver-data-1:/mnt/tserver
    environment:
      SERVICE_5433_NAME: ysql
      SERVICE_9042_NAME: ycql
      SERVICE_6379_NAME: yedis
      SERVICE_9000_NAME: yb-tserver
    healthcheck:
      test: "yb-ts-cli is_server_ready | grep 'server is ready'"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    depends_on:
      - yb-master

  typesense:
    build: ./dockerfiles/typesense
    command: --data-dir=/data --api-key=searchkey
    ports:
      - "8108:8108"
    restart: on-failure:10
    healthcheck:
      test: "curl -f http://localhost:8108/health || exit"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - typesense-data:/data

volumes:
  yb-master-data-1:
  yb-tserver-data-1:
  typesense-data:


